#!/bin/bash

#
# Copyright 2017-present Pandora Media, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Fetch the Kafka binaries into a local "kafka" dir.

set -e -o pipefail

function verify_md5_hash {
    FILE=$1
    HASH=$2
    set +e
    if type md5 > /dev/null; then
        # OSX
        set -e
        if [ "$(md5 $FILE | awk '{ print $4 }')" == "$HASH" ]; then
            return 0
        else
            echo md5 hash checked failed on $FILE
            return 1
        fi
    elif type md5sum > /dev/null; then
        # Linux
        set -e
        if [ "$(md5sum $FILE  | awk '{ print $1 }')" == "$HASH" ]; then
            return 0
        else
            echo md5sum hash checked failed on $FILE
            return 1
        fi
    else
        echo verify_md5_hash_failed: could not find md5 or md5sum
        return 1
    fi
}

TGZ=kafka_2.12-2.7.0.tgz
if [ ! -f $TGZ ]; then
    echo Downloading Kafka...
    curl -L http://www-us.apache.org/dist/kafka/2.7.0/$TGZ -o $TGZ
fi

# Always verify, in case of re-runs
verify_md5_hash $TGZ 9127875811b8a7b7a5b84d0c4c19874b
